# docker-compose.yml
services:
  mcp-pbm-demo:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -lc 'uvicorn server.pbm_server:app --host 0.0.0.0 --port 7860 & python -m client.app'
    ports:
      - "7860:7860"   # FastAPI API
      - "7861:7861"   # Gradio UI
    environment:
      PBM_API_BASE: "http://localhost:7860"   # UI calls API
      GRADIO_HOST: "0.0.0.0"
      GRADIO_PORT: "7861"                     # force UI port
      TOGETHER_API_KEY: "${TOGETHER_API_KEY:-}"
      TOGETHER_MODEL: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
